import { StyleSheet } from 'react-native';
import { Typography } from '../../../theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  header: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: Typography.fontFamily.bold,
    color: '#1E1E26',
  },
  headerRight: {
    width: 40,
  },
  profileTop: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  avatarContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: '#0D9488',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 112,
    height: 112,
    borderRadius: 56,
  },
  name: {
    fontSize: 24,
    fontFamily: Typography.fontFamily.bold,
    color: '#1E1E26',
    marginBottom: 8,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 12,
  },
  badge: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  badgeText: {
    fontSize: 12,
    color: '#6B7280',
    fontFamily: Typography.fontFamily.medium,
  },
  stateToggleRow: {
    flexDirection: 'row',
    backgroundColor: '#ECEFF3',
    borderRadius: 16,
    padding: 4,
    marginBottom: 8,
  },
  stateToggleBtn: {
    flex: 1,
    height: 34,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stateToggleBtnActive: {
    backgroundColor: '#FFFFFF',
  },
  stateToggleText: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.medium,
    color: '#64748B',
  },
  stateToggleTextActive: {
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 16,
  },
  cardContent: {
    width: '100%',
  },
  nextCheckinHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardPreTitle: {
    fontSize: 10,
    color: '#9CA3AF',
    letterSpacing: 0.5,
    fontFamily: Typography.fontFamily.bold,
    textTransform: 'uppercase',
  },
  scheduleBtn: {
    backgroundColor: '#1E1E26',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  scheduleBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: Typography.fontFamily.bold,
  },
  nextCheckinText: {
    fontSize: 18,
    color: '#9CA3AF',
    fontFamily: Typography.fontFamily.medium,
  },
  nextCheckinValue: {
    fontSize: 18,
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
  },
  nextCheckinTime: {
    fontSize: 14,
    color: '#6B7280',
    fontFamily: Typography.fontFamily.medium,
  },
  statusBadge: {
    backgroundColor: '#F0FDFA',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusBadgeText: {
    color: '#0D9488',
    fontSize: 12,
    fontFamily: Typography.fontFamily.bold,
  },
  ctaButton: {
    height: 56,
    borderRadius: 28,
    marginBottom: 32,
    backgroundColor: '#1E1E26',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.bold,
    color: '#9CA3AF',
  },
  viewAllLink: {
    fontSize: 13,
    color: '#0D9488',
    fontFamily: Typography.fontFamily.bold,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 16,
  },
  programCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 16,
  },
  programCardSmall: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 20,
    marginBottom: 16,
  },
  programTitle: {
    fontSize: 22,
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
    marginVertical: 12,
  },
  programTitleSmall: {
    fontSize: 22,
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
    marginTop: 8,
  },
  progressText: {
    fontSize: 14,
    color: '#4B5563',
    fontFamily: Typography.fontFamily.medium,
    marginBottom: 12,
  },
  progressBarContainer: {
    width: '100%',
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F3F4F6',
    overflow: 'hidden',
    marginBottom: 16,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#0D9488',
    borderRadius: 4,
  },
  lastReorder: {
    fontSize: 13,
    color: '#6B7280',
    fontFamily: Typography.fontFamily.medium,
    marginBottom: 12,
  },
  reorderBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF7ED',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFEDD5',
  },
  reorderBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F97316',
    marginRight: 6,
  },
  reorderBadgeText: {
    fontSize: 12,
    color: '#C2410C',
    fontFamily: Typography.fontFamily.bold,
  },
  insightsSection: {
    marginTop: 16,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
  },
  insightGroup: {
    marginTop: 20,
    paddingTop: 20,
  },
  insightRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  insightBlock: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 16,
  },
  insightLabel: {
    fontSize: 9,
    color: '#64748B',
    fontFamily: Typography.fontFamily.bold,
    letterSpacing: 0.5,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  insightValue: {
    fontSize: 20,
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
    marginBottom: 4,
  },
  insightValueTeal: {
    fontSize: 20,
    color: '#0D9488',
    fontFamily: Typography.fontFamily.bold,
    marginBottom: 4,
  },
  insightSub: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: Typography.fontFamily.medium,
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 16,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  detailLabel: {
    fontSize: 14,
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
  },
  detailValue: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: Typography.fontFamily.medium,
  },
});

export default styles;
