import { StyleSheet } from 'react-native';
import { Typography } from '../../../theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  header: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: Typography.fontFamily.bold,
    color: '#1E1E26',
  },
  headerRight: {
    width: 40,
  },
  profileTop: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  avatarContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: '#0D9488',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 112,
    height: 112,
    borderRadius: 56,
  },
  name: {
    fontSize: 24,
    fontFamily: Typography.fontFamily.bold,
    color: '#1E1E26',
    marginBottom: 8,
  },
  medTag: {
    backgroundColor: '#7399FA',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 4,
    alignSelf: 'center',
  },
  medTagText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 10,
    color: '#E3DDFF',
    letterSpacing: 0.5,
  },
  badge: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 12,
  },
  badgeText: {
    fontSize: 12,
    color: '#6B7280',
    fontFamily: Typography.fontFamily.medium,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 16,
  },
  cardPreTitle: {
    fontSize: 10,
    color: '#9CA3AF',
    letterSpacing: 0.5,
    fontFamily: Typography.fontFamily.bold,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  programTitle: {
    fontSize: 22,
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
    marginBottom: 12,
  },
  progressText: {
    fontSize: 14,
    color: '#4B5563',
    fontFamily: Typography.fontFamily.medium,
    marginBottom: 12,
  },
  progressBarContainer: {
    width: '100%',
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F3F4F6',
    overflow: 'hidden',
    marginBottom: 10,
  },
  progressBarFill: {
    width: '50%',
    height: '100%',
    backgroundColor: '#0D9488',
    borderRadius: 4,
  },
  lastReorder: {
    fontSize: 13,
    color: '#6B7280',
    fontFamily: Typography.fontFamily.medium,
    marginBottom: 10,
  },
  reorderBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFEDD5',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reorderBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F97316',
    marginRight: 6,
  },
  reorderBadgeText: {
    fontSize: 12,
    color: '#C2410C',
    fontFamily: Typography.fontFamily.bold,
  },
  insightRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  insightBlock: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 16,
  },
  insightLabel: {
    fontSize: 9,
    color: '#64748B',
    fontFamily: Typography.fontFamily.bold,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  insightValue: {
    fontSize: 20,
    color: '#1E1E26',
    fontFamily: Typography.fontFamily.bold,
    marginBottom: 4,
  },
  insightValueTeal: {
    fontSize: 20,
    color: '#0D9488',
    fontFamily: Typography.fontFamily.bold,
    marginBottom: 4,
  },
  insightSub: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: Typography.fontFamily.medium,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
  },
  cardContent: {
    width: '100%',
  },
  nextCheckinHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  nextCheckinText: {
    fontSize: 18,
    color: '#9CA3AF',
    fontFamily: Typography.fontFamily.medium,
  },
  scheduleBtn: {
    backgroundColor: '#1E1E26',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: -2,
  },
  scheduleBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: Typography.fontFamily.bold,
  },
  ctaButton: {
    height: 56,
    borderRadius: 28,
    marginBottom: 16,
    marginVertical: 0,
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 14,
    color: '#4B5563',
    fontFamily: Typography.fontFamily.bold,
  },
  detailValue: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: Typography.fontFamily.medium,
  },
});

export default styles;
