import { StyleSheet } from 'react-native';
import { Colors, Typography } from '../../../theme';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  header: {
    marginTop: 20,
    marginBottom: 20,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  toggleButton: {
    flex: 1,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  toggleButtonText: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.medium,
    color: '#475569',
    textAlign: 'center',
  },
  notificationBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F0FDFA',
    borderWidth: 1,
    borderColor: '#0D9488',
    borderRadius: 16,
    paddingTop: 18,
    paddingBottom: 18,
    paddingHorizontal: 12,
    marginBottom: 16,
    position: 'relative',
  },
  notificationIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#CCFBF1',
    marginRight: 10,
    marginTop: 4,
  },
  notificationTextWrap: {
    flex: 1,
    paddingTop: 2,
    paddingBottom: 2,
  },
  notificationTitle: {
    fontSize: 15,
    fontFamily: Typography.fontFamily.bold,
    color: '#134E4A',
  },
  notificationSubtitle: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.medium,
    color: '#0F766E',
    marginTop: 2,
  },
  notificationClose: {
    marginLeft: 8,
    marginTop: -2,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  notificationDots: {
    position: 'absolute',
    right: 12,
    bottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  notificationDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#0D9488',
  },
  notificationDotInactive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#BFEDE8',
  },
  headerTitle: {
    fontSize: 28,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.dark,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    // Shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardLabel: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.medium,
    color: '#94A3B8',
    letterSpacing: 0.5,
  },
  programRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  programTitle: {
    fontSize: 22,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.dark,
  },
  cardSubtitle: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.regular,
    color: '#64748B',
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: -6,
  },
  cardButton: {
    flex: 1,
    height: 48,
    marginVertical: 0,
    marginHorizontal: 6,
  },
  cardButtonText: {
    fontSize: 14,
  },
  reminderWait: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.regular,
    color: '#64748B',
    marginBottom: 4,
  },
  reminderTitle: {
    fontSize: 32,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.dark,
    marginBottom: 20,
  },
  reminderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  reminderIcon: {
    marginRight: 10,
  },
  reminderTextRow: {
    flex: 1,
    justifyContent: 'center',
  },
  reminderInline: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  reminderLabel: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.medium,
    color: Colors.dark,
  },
  reminderAction: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.regular,
    color: '#94A3B8',
    marginLeft: 8,
  },
  sectionHeader: {
    marginVertical: 4,
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.dark,
  },
  actionCard: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionCardContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  actionIcon: {
    marginRight: 12,
  },
  actionContent: {
    flex: 1,
  },
  actionTitle: {
    fontSize: 16,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.dark,
  },
  actionSubtitle: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.regular,
    color: '#64748B',
    marginTop: 2,
  },
  comingSoonOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#737373EB',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  comingSoonText: {
    fontSize: 18,
    fontFamily: Typography.fontFamily.bold,
    color: '#EFEFEF',
    textAlign: 'center',
  },
  comingUpCard: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 20,
    marginBottom: 24,
  },
  comingUpHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 16,
  },
  comingUpText: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.medium,
    color: '#6B7280',
    marginTop: 6,
    flex: 1,
    marginRight: 10,
  },
  badge: {
    backgroundColor: '#F0FDFA',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: {
    fontSize: 10,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.primary,
  },
  doctorImage: {
    width: '100%',
    height: 180,
    justifyContent: 'center',
    alignItems: 'center',
  },
  doctorImageStyle: {
    borderRadius: 16,
  },
  referButton: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
    gap: 10,
  },
  referText: {
    fontSize: 14,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.dark,
    letterSpacing: 1,
  },
});

export default styles;
